"""
Phase 8 End-to-End Demonstration

Flow:
User Request -> Intelligence -> AISystemSpecification -> AI Creation Engine ->
GeneratedAISystem -> Execution -> Result -> Evaluation
"""
import asyncio
import time
import json
from pprint import pprint

# 1. Container & Dependencies
from core.container import ApplicationContainer
from core.creation.builder import AISystemBuilder
from core.creation.capabilities import CapabilityRegistry
from core.creation.standard_capabilities import (
    RetrievalCapability, ChatCapability, VerificationCapability, PlanningCapability
)

# 2. Intelligence
from intelligence.spec_generator import generate_specification
from intelligence.evaluation import (
    EvalSample, EvalDataset, EvalPrediction, EvaluationRunner,
    SuccessRateMetric, MeanLatencyMetric, ContainsReferenceMetric
)
from core.graph.contracts import GraphState
from core.domain import Query

def run_demo():
    print("============================================================")
    print(" PHASE 8: SYNTERA AI ENGINE — END-TO-END DEMO")
    print("============================================================\n")
    
    # Setup Container & Intelligence
    print("[1] Initializing Container and Intelligence Core...")
    container = ApplicationContainer()
    intelligence = container.get_intelligence()
    
    # We need the router for spec generation
    router = intelligence.router
    print(f"    - Default Intelligence Provider: {router._default.profile.name}")
    print(f"    - Backend: {router._default.profile.provider}\n")
    
    user_request = "Create an AI research assistant that can retrieve evidence, reason over documents, use tools and produce verified answers."
    
    print("============================================================")
    print(f" USER REQUEST: '{user_request}'")
    print("============================================================\n")
    
    # 2. Natural Language -> AISystemSpecification
    print("[2] SYNTERA INTELLIGENCE -> AISystemSpecification")
    print("    - Running IntelligenceCore.structured_generate() to build spec...")
    
    start_time = time.time()
    spec, result = generate_specification(user_request, router)
    elapsed = time.time() - start_time
    
    if not result.success:
        print(f"    ! Failed to generate spec: {result.error}")
        print(f"    ! Validation errors: {result.validation_errors}")
        return
        
    print(f"    - Spec Generated in {elapsed:.2f}s!")
    print(f"    - System Name: {spec.identity.name}")
    print(f"    - Purpose: {spec.purpose}")
    print(f"    - Capabilities Requested: {[c.name for c in spec.capabilities]}\n")
    
    # Ensure requested capabilities map to our registered ones
    requested_caps = [c.name for c in spec.capabilities]
    # For this demo, force planning and retrieval if not correctly parsed
    if "planning" not in requested_caps:
        from core.creation.domain import CapabilityRequirement
        spec.capabilities.append(CapabilityRequirement(name="planning"))
    if "retrieval" not in requested_caps:
        from core.creation.domain import CapabilityRequirement
        spec.capabilities.append(CapabilityRequirement(name="retrieval"))
    
    # 3. AI Creation Engine
    print("[3] AI CREATION ENGINE -> GeneratedAISystem")
    registry = CapabilityRegistry()
    registry.register(RetrievalCapability())
    registry.register(ChatCapability())
    registry.register(VerificationCapability())
    registry.register(PlanningCapability())
    
    # We must also register the core components into the DI container
    from providers.embeddings import EmbeddingProvider
    from retrieval.assembler import DefaultContextAssembler
    from core.contracts import BaseQueryProcessor, Query
    from vectorstore.qdrant_store import QdrantStore
    from retrieval.reranker import CrossEncoderReranker
    from verification.grounding import CitationVerifier
    
    class PassthroughQueryProcessor(BaseQueryProcessor):
        def process(self, query: Query) -> list[Query]:
            return [query]
            
    container.registry.register_embedding_provider("sentence_transformers", lambda: EmbeddingProvider())
    container.registry.register_retriever("qdrant", lambda embedding_provider: QdrantStore(embedding_provider=embedding_provider, collection_name="demo"))
    container.registry.register_reranker("cross_encoder", lambda: CrossEncoderReranker())
    container.registry.register_context_assembler("default", lambda: DefaultContextAssembler())
    container.registry.register_query_processor("passthrough", lambda: PassthroughQueryProcessor())
    container.registry.register_verifier("citation", lambda: CitationVerifier())
    
    builder = AISystemBuilder(registry, container)
    
    # Filter out unregistered capabilities generated by the LLM
    spec.capabilities = [c for c in spec.capabilities if registry.has(c.name)]
    
    print(f"    - Building AI System from Specification...")
    ai_system = builder.build(spec)
    
    print(f"    - Build Successful! System Status: {ai_system.metadata['status']}")
    print(f"    - Resolved Capabilities: {ai_system.resolved_capabilities}")
    print(f"    - Graph Nodes: {list(ai_system.execution_graph.nodes.keys())}")
    print(f"    - Entry Point: {ai_system.execution_graph.entry_point}\n")
    
    # 4. Execution
    print("[4] EXECUTION -> REAL MODEL + RAG + TOOLS -> RESULT")
    test_query = "What architectural principle was mandated for the Phase 5B execution engine?"
    print(f"    - Executing Task: '{test_query}'")
    
    initial_state = GraphState(
        query=Query(text=test_query),
        documents=[],
        context=None,
        generation_result=None,
        verification_result=None,
        plan=None,
        observations=[],
        current_task_idx=0,
        iteration=0,
        max_iterations=5,
        final_answer=None,
        error=None,
        metadata={}
    )
    
    exec_start = time.time()
    try:
        # We need an event loop for async nodes, though most are synchronous
        exec_result = ai_system.execution_graph.run(initial_state)
        exec_elapsed = time.time() - exec_start
        
        print(f"    - Execution Completed in {exec_elapsed:.2f}s!")
        print(f"    - Final Answer:")
        print(f"      {exec_result.final_state.final_answer or exec_result.final_state.error}\n")
        
        if exec_result.final_state.plan:
            print("    - Agentic Plan Executed:")
            for t in exec_result.final_state.plan.tasks:
                print(f"      * {t.description} (Tool: {t.tool_name}) -> {t.status}")
                
    except Exception as e:
        print(f"    ! Execution Failed: {e}")
        return

    # 5. Evaluation
    print("\n[5] EVALUATION")
    print("    - Running benchmark dataset against the Generated AI System...")
    
    dataset = EvalDataset(
        name="demo_benchmark",
        samples=[
            EvalSample(id="1", input="What architectural principle was mandated for Phase 5B?", reference="Execution engine, not a hardcoded pipeline")
        ]
    )
    
    def evaluate_system(input_text: str) -> str:
        state = GraphState(
            query=Query(text=input_text),
            documents=[], context=None, generation_result=None,
            verification_result=None, plan=None, observations=[],
            current_task_idx=0, iteration=0, max_iterations=3,
            final_answer=None, error=None, metadata={}
        )
        res = ai_system.execution_graph.run(state)
        if res.final_state.error:
            raise RuntimeError(res.final_state.error)
        return res.final_state.final_answer or ""
        
    runner = EvaluationRunner(metrics=[
        SuccessRateMetric(),
        MeanLatencyMetric(),
        ContainsReferenceMetric()
    ])
    
    eval_result = runner.run(dataset, evaluate_system, system_name=ai_system.identity.name)
    
    print(f"    - Evaluation Run: {eval_result.run_id}")
    for metric in eval_result.metrics:
        print(f"      * {metric.name}: {metric.value:.3f}")
        
    print("\n============================================================")
    print(" PHASE 8: DEMONSTRATION COMPLETE")
    print("============================================================")

if __name__ == "__main__":
    run_demo()
